name: Build & deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm ci

      - name: Run prettier check
        run: npm run format:check

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ${{ secrets.PROD_MAIN_URL }}
