export interface Greeting {
  language: string;
  greeting: string;
}

export const greetings: Greeting[] = [
  { language: 'Arabic', greeting: 'Marhaba' },
  { language: 'Bavarian', greeting: 'Grüß Gott' },
  { language: 'Bengali', greeting: 'Namaskar' },
  { language: 'Bulgarian', greeting: 'Zdraveite' },
  { language: 'Catalan', greeting: 'Hola' },
  { language: 'Chamorro', greeting: 'Hafa adai' },
  { language: 'Chinese', greeting: 'Nǐ hǎo' },
  { language: 'Croatian', greeting: 'Dobar dan' },
  { language: 'Danish', greeting: 'God dag' },
  { language: 'Dutch', greeting: 'Hoi' },
  { language: 'Finnish', greeting: 'Hyvää päivää' },
  { language: 'French', greeting: 'Bonjour' },
  { language: 'Gaeilge', greeting: 'Dia dhuit' },
  { language: 'German', greeting: 'Guten tag' },
  { language: 'Greek', greeting: 'Yasou' },
  { language: 'Hebrew', greeting: 'Shalom' },
  { language: 'Hindi', greeting: 'Namaste' },
  { language: 'Hungarian', greeting: 'Jó napot' },
  { language: 'Icelandic', greeting: 'Góðan dag' },
  { language: 'Igbo', greeting: 'Nde-ewo' },
  { language: 'Indonesian', greeting: 'Selamat siang' },
  { language: 'Italian', greeting: 'Buongiorno' },
  { language: 'Japanese', greeting: 'Konnichiwa' },
  { language: 'Korean', greeting: 'Ahnnyong haseyo' },
  { language: 'Latin', greeting: 'Salve' },
  { language: 'Lithuanian', greeting: 'Sveiki' },
  { language: 'Luxembourgish', greeting: 'Moïen' },
  { language: 'Maltese', greeting: 'Bonġu' },
  { language: 'Nahuatl', greeting: 'Niltze' },
  { language: 'Nepali', greeting: 'Namastē' },
  { language: 'Norwegian', greeting: 'Hallo' },
  { language: 'Persian', greeting: 'Salam' },
  { language: 'Polish', greeting: 'Cześć' },
  { language: 'Portuguese', greeting: 'Olá' },
  { language: 'Romanian', greeting: 'Bună ziua' },
  { language: 'Russian', greeting: 'Zdravstvuyte' },
  { language: 'Serbian', greeting: 'Zdravo' },
  { language: 'Slovak', greeting: 'Ahoj' },
  { language: 'Spanish', greeting: 'Hola' },
  { language: 'Swahili', greeting: 'Hujambo' },
  { language: 'Swedish', greeting: 'Hallå' },
  { language: 'Tahitian', greeting: 'Ia orna' },
  { language: 'Thai', greeting: 'Sawasdee' },
  { language: 'Tsonga', greeting: 'Avuxeni' },
  { language: 'Turkish', greeting: 'Merhaba' },
  { language: 'Ukrainian', greeting: 'Zdravstvuyte' },
  { language: 'Urdu', greeting: 'Assalamo aleikum' },
  { language: 'Vietnamese', greeting: 'Xin chào' },
  { language: 'Welsh', greeting: 'Shwmae' },
  { language: 'Zulu', greeting: 'Sawubona' },
];
